-- ~/.config/nvim/lua/plugins/mason.lua
-- C:/Users/user_name/AppData/Local/nvim/lua/plugins/mason.lua
-- Mason LSPs, Formatters, Linters and DAPs
return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {

        -- LSP servers
        "arduino-language-server",
        "asm-lsp",
        "cmake-language-server",
        "cobol-language-support",
        "copilot-language-server",
        "css-lsp",
        "css-variables-language-server",
        "cssmodules-language-server",
        "django-template-lsp",
        "docker-compose-language-service",
        "docker-language-server",
        "dockerfile-language-server",
        "html-lsp",
        "json-lsp",
        "kotlin-language-server",
        "kotlin-lsp",
        "laravel-ls",
        "lua-language-server",
        "postgres-language-server",
        "python-lsp-server",
        "rust-analyzer",
        "terraform",
        "terraform-ls",
        "typescript-language-server",
        "vim-language-server",
        "yaml-language-server",

        -- Formatters
        "asmfmt",
        "clang-format",
        "djlint",
        "htmlbeautifier",
        "jq",
        "json-repair",
        "markdown-toc",
        "prettier",
        "pretty-php",
        "prettydiff",
        "shfmt",
        "sql-formatter",
        "stylua",
        "tree-sitter-cli",
        "xmlformatter",
        "yamlfmt",

        -- Linters
        "cmakelang",
        "cmakelint",
        "codespell",
        "cpplint",
        "dotenv-linter",
        "eslint_d",
        "gitlint",
        "jsonlint",
        "markdownlint",
        "phpcs",
        "phpmd",
        "phpstan",
        "pylint",
        "pylyzer",
        "pymarkdownlnt",
        "shellcheck",
        "sqruff",
        "standardjs",
        "stylelint",
        "textlint",
        "ts-standard",
        "yamlfix",
        "yamllint",

        -- DAPs
        "cpptools",
        "debugpy",
        "java-debug-adapter",
        "java-test",
        "js-debug-adapter",
        "kotlin-debug-adapter",
        "local-lua-debugger-vscode",
        "perl-debug-adapter",
        "php-debug-adapter",
      },
    },
  },
}
