-- ~/.config/nvim/lua/plugins/mason.lua
-- C:/Users/user_name/AppData/Local/nvim/lua/plugins/mason.lua
-- Mason LSPs, Formatters, Linters and DAPs
return {
    {
        "mason-org/mason.nvim",
        opts = {
            ensure_installed = {
                -- LSP servers
                "arduino-language-server",
                "clangd",
                "cmake-language-server",
                "cobol-language-support",
                "copilot-language-server",
                "csharp-language-server",
                "css-lsp",
                "css-variables-language-server",
                "cssmodules-language-server",
                "django-template-lsp",
                "docker-compose-language-service",
                "docker-language-server",
                "dockerfile-language-server",
                "html-lsp",
                "json-lsp",
                "kotlin-language-server",
                "laravel-ls",
                "lua-language-server",
                "postgres-language-server",
                "python-lsp-server",
                "rust-analyzer",
                "terraform-ls",
                "typescript-language-server",
                "vim-language-server",
                "yaml-language-server",

                -- Formatters
                "asmfmt",
                "djlint",
                "jq",
                "json-repair",
                "markdown-toc",
                "prettydiff",
                "prettier",
                "pretty-php",
                "shfmt",
                "sql-formatter",
                "stylua",
                "typstfmt",
                "xmlformatter",
                "yamlfmt",

                -- Linters
                "cmakelang",
                "cmakelint",
                "codespell",
                "cpplint",
                "cspell",
                "cspell-lsp",
                "dotenv-linter",
                "eslint_d",
                "gitlint",
                "htmlhint",
                "jsonlint",
                "ktlint",
                "markdownlint",
                "phpcs",
                "phpmd",
                "phpstan",
                "pylint",
                "pylyzer",
                "pymarkdownlnt",
                "shellcheck",
                "sqlfluff",
                "standardjs",
                "stylelint",
                "stylelint-lsp",
                "textlint",
                "ts-standard",
                "yamllint",

                -- DAPs
                "cpptools",
                "go-debug-adapter",
                "java-debug-adapter",
                "java-test",
                "js-debug-adapter",
                "kotlin-debug-adapter",
                "local-lua-debugger-vscode",
                "perl-debug-adapter",
                "php-debug-adapter",
            },
        },
    },
}
